@startuml
class BattleRunner <<Client>> {
}

class GamePet <<Context>> {
    - SPECIALABILITY: Specialability
    + <<Constructor>> GamePet()
    + getSpecialAbility(): SpecialAbility
}

interface SpecialAbility <<Strategy>> {
    + useSpecialAbility(self: GamePet, other: GamePet, cli: CommandLineInterface) : void
}

class BuffSelf <<ConcreteStrategyA>> {
    + useSpecialAbility(self: GamePet, other: GamePet, cli: CommandLineInterface) : void
}

class HealSelf <<ConcreteStrategyB>> {
    + useSpecialAbility(self: GamePet, other: GamePet, cli: CommandLineInterface) : void
}

class HealBoth <<ConcreteStrategyC>> {
    + useSpecialAbility(self: GamePet, other: GamePet, cli: CommandLineInterface) : void
}

class DebuffEnemy <<ConcreteStrategyD>> {
    + useSpecialAbility(self: GamePet, other: GamePet, cli: CommandLineInterface) : void
}

BattleRunner --> GamePet : > uses
GamePet *--> "1" SpecialAbility
SpecialAbility <|.. BuffSelf
SpecialAbility <|.. HealSelf
SpecialAbility <|.. HealBoth
SpecialAbility <|.. DebuffEnemy

@enduml
